export const states = {
  init: "is-init",
  active: "is-active",
  fixed: "is-fixed",
  scrolling: "is-scrolling",
  hover: "is-hover",
  searching: "is-searching",
  filled: "is-filled",
  focus: "is-focus",
  open: "is-open",
  disabled: "is-disabled",
  highlight: "is-highlight",
  select: "is-selected",
  flip: "is-flip",
  error: "is-error",
  warning: "is-warning",
  valid: "is-valid",
  animate: "is-animate",
  success: "is-success",
  hidden: "is-hidden",
  show: "is-showed",
  checked: "is-checked",
  empty: "is-empty",
  target: "is-target",
};
